### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by poteirard** [moroshko/react-scanner#72]
I found that I get a `Failed to parse` to some files.

After a bit of debugging I found that it's because the use of `satisfies` in TS files (feature from TS 4.9).

I guess the library needs a lot of updating (@typescript-eslint/typescript-estree, typescript, ...).

Is this library still maintained? and if not, does anyone know good alternatives?

Thanks!

**Comment by moroshko** [comment]
@poteirard I'm short on time at the moment, happy to give you access if you'd like to upgrade the deps and fix this. Please DM me on twitter @moroshko if you do.

**Comment by poteirard** [comment]
@moroshko apparently I can't send you a message in Twitter unless I pay now 🙄 

I have created a PR here #73 

Thanks 🙏

**Comment by Golodhros** [comment]
> @moroshko apparently I can't send you a message in Twitter unless I pay now 🙄
> 
> I have created a PR here #73
> 
> Thanks 🙏

Just used your fork, and it worked better, but still getting parsed errors.
Any insights about how to debug it?
